# rust backend actix-web

GET http://localhost:8080/sushi

###
# {} 空のリクエストを送って、validationの確認
POST http://localhost:8080/addsushi
content-type: application/json

{
  "sushi_name":"ootoro"
}

###

PATCH http://localhost:8080/updatesushi/abcdefg1111

### test surrealDB

GET http://localhost:8000/version HTTP/1.1